bangumi/frontend

packages/website/.env
packages/website/package.json
packages/website/src/App.tsx
packages/website/src/api/character.ts
packages/website/src/api/request.ts
packages/website/src/types/common.ts
pnpm-lock.yaml

加了个axios请求库，写法很土，环境变量是放在对应workplace下面吗
两个问题
* import.meta无法通过jest https://github.com/facebook/jest/issues/4842 可能需要改一下jest配置~~我不知道怎么改~~
* 后端字段现在是用的下划线，但是前端eslint设置的是驼峰的 @Trim21

feat: add axios request test

---

packages/website/src/App.test.tsx
packages/website/src/App.tsx
packages/website/src/api/api.test.ts
packages/website/src/api/request.ts
packages/website/src/api/subject.ts
packages/website/src/types/common.ts

添加了Subject 类型, 并由 #31 ，将请求到的数据的键全部进行驼峰处理。（也许之后可以放到 utils 里？）

feat: add subject type, convert api to camelcase

---

packages/website/src/api/request.ts
packages/website/src/mocks/handlers.ts
packages/website/src/mocks/utils.ts

- refactor api `baseURL`
- fix typo: `underscodeToCamelcase` -> `underscoreToCamelcase`
- fix msw types
`underscoreToCamelcase` 是否有存在的必要？我觉得对数据的操作应该和 API 接口返回的格式相同。前端每一次请求接口都会调用 `underscoreToCamelcase` 也是额外的性能损失 @Ayase-252 
目前用公共 API 的话也可以用 https://www.npmjs.com/package/bgm-types 减少手写 TS 接口的麻烦操作（

refactor: refactor api `baseURL`

---

codecov.yaml

现在 CI 的状态是有点问题的。有时会有因为测试覆盖率下降产生的错误。
分开对组件库测试覆盖与网站业务代码测试覆盖率的要求。

ci: adjust codecov requirement

---

.eslintrc.js
package.json
packages/utils/bbcode/html.ts
packages/website/src/pages/login/index.tsx
pnpm-lock.yaml

主要还是版本导致的，`@typescript-eslint/eslint-plugin` 5.8.1 没有这个问题，在 react-18 那个 PR 里被升级了。
> https://github.com/typescript-eslint/typescript-eslint/issues/4619

chore: no-misused-promises

---

packages/website/src/components/Header/style.module.less
packages/website/vite.config.ts

删除 samesite 以正确设置 stage 模式下的 cookie，导航栏在 1440px 宽度下会和 logo 挤在一起，一起修了。

fix: nav spacing

---

package.json

fix: fix required engines

---

packages/design/components/Avatar/__test__/Avatar.test.tsx
packages/design/components/Button/__test__/Button.test.tsx
packages/design/components/Typography/__test__/Texts.spec.tsx
packages/website/tsconfig.json

修复三个组件的测试文件内的类型报错。
website 的 tsconfig 应该包含 `vite.config.ts` 和 `jest-setup.ts`。

fix(design): test type and `include` of tsconfig

---

packages/design/components/Avatar/index.tsx
packages/design/components/Divider/index.tsx
packages/design/components/Image/index.tsx
packages/design/components/Input/index.tsx
packages/design/components/Menu/MenuItem.tsx
packages/design/components/Menu/index.tsx
packages/design/components/Pagination/index.tsx
packages/design/components/Rate/index.tsx
packages/design/components/Tab/index.tsx
packages/design/components/Typography/Link.stories.tsx
packages/design/components/Typography/Typography.stories.tsx

- Topology -> Typography
- 把普通注释换成文档注释，不然Storybook不会显示在文档里，IDE也没有提示
- Before:
- After:

fix: storybook typo & doc

---

packages/website/package.json
packages/website/vite.config.ts
pnpm-lock.yaml

在构建时移除 `data-testid` 这种自定义的数据属性，因为其只在测试环境中有用

chore: remove data-testid in prod

---

packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
packages/utils/bbcode/react.tsx

- 循环渲染的时候有一部分子元素没有指定 Key:
- 换行符应该加在第一个子元素后面而不是前面：
```react
<React.Fragment>
<React.Fragment>
<React.Fragment />
<br /> <------ 这里
ss[b]加粗
</React.Fragment>
换行了[/b](bgm38) [/fafa [code]
</React.Fragment>
```

fix: BBCode rendering line breaks & react key

---

packages/design/components/EditorForm/Editor.tsx
packages/design/components/EditorForm/style/index.less

- 将额外参数传递给 textarea
- 根据设计稿将文字大小改为 16px
- 文本域右侧也应有 padding
**Before:**
**After:**

fix(Editor): pass down extra props, fix font size & padding

---

packages/design/components/EditorForm/Editor.tsx
packages/design/components/EditorForm/EditorForm.stories.tsx
packages/design/components/EditorForm/__test__/Editor.spec.tsx
packages/design/components/EditorForm/__test__/EditorForm.test.tsx
packages/design/components/EditorForm/index.tsx
packages/design/components/Topic/ReplyForm.tsx

为了更方便地配合 react-hook-form 使用：
- 让 Editor 直接暴露 textarea 的 ref，在校验不通过时能够自动聚焦输入框
- 将 content 参数重命名为 value，与 react-hook-form 匹配，在 render 函数中可以直接使用 `{...field}`
- 向下传递 react-hook-form 要求的两个参数 `name` 和 `onBlur`
使用方法：
```javascript
<Controller
name='content'
control={control}
render={({ field }) => (
<EditorForm
onConfirm={() => {
handleSubmit(onSubmit)();
}}
{...field}
/>
)}
/>
```

refactor(Editor): forward textarea ref & props

---

packages/design/components/Button/__test__/Button.test.tsx
packages/design/components/Button/__test__/__snapshots__/Button.test.tsx.snap
packages/design/components/Button/button.stories.tsx
packages/design/components/Button/index.tsx
packages/design/components/Button/style/index.less
packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
packages/design/components/EditorForm/index.tsx
packages/design/components/EditorForm/style/index.less
packages/design/components/Form/Form.stories.tsx
packages/design/components/Topic/Comment.tsx
packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap
packages/design/components/Topic/style/Comment.less
packages/website/src/components/Header/index.tsx
packages/website/src/components/Header/style.module.less
packages/website/src/pages/index/group/topic/[id]/index.module.less
packages/website/src/pages/index/group/topic/[id]/index.tsx
packages/website/src/pages/index/subject/[id]/wiki/common.module.less
packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
packages/website/src/pages/login/index.module.less
packages/website/src/pages/login/index.tsx

此前 design 包里提供的按钮类型不能完全满足要求，导致各个地方都重复用了自定义样式，与设计师[讨论](https://bangumiworkspace.slack.com/archives/C02RY7CKGAW/p1675045471609809?thread_ts=1674896271.461799&cid=C02RY7CKGAW)后更新了一下设计系统，整理了按钮类型，增加了对不同大小和颜色的支持，并对不符合设计稿的地方进行了修正，清理了样式表。
https://pr-324-storybook--bangumi-next.netlify.app/?path=/docs/modern-button--primary

refactor: update button design system

---

packages/design/components/Form/index.tsx
packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx

e.g. [wiki edit page](http://localhost:5173/subject/363612/wiki/edit_detail) 的 monaco-editor 和 textarea 无法使用 enter 键换行
@FoundTheWOUT 原来的这个 `preventDefault` 是有何用意？

fix: enter key not working in form

---

packages/design/components/Button/__test__/Button.test.tsx
packages/design/components/Button/__test__/__snapshots__/Button.test.tsx.snap
packages/design/components/Button/button.stories.tsx
packages/design/components/Button/index.tsx
packages/design/components/Button/style/index.less
packages/design/components/Typography/Link.tsx
packages/design/components/Typography/__test__/Link.spec.tsx
packages/design/components/Typography/__test__/__snapshots__/Link.spec.tsx.snap
packages/design/components/Typography/style/Link.less
packages/website/src/pages/index/group/components/GroupInfo.tsx

close #329
由于 Less 编译的缘故，`.bgm-link` 的样式会覆盖 `.bgm-button` 的样式，本来可以将 `.bgm-button` 细化为 `a.bgm-button` 和 `button.bgm-button` 提高优先级，但这样又会影响在 Button 上加的 class，所以还是在 `.bgm-link` 做了改动

feat: button link

---

.github/mergify.yml
CONTRIBUTING.md

GitHub branch protection rule 没有修改，仍然是 1 个approval，只是修改了 bot 的自动合并条件。
避免 https://github.com/bangumi/frontend/pull/320#issuecomment-1427847872

ci: require 2 approval to auto-merging

---

packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
packages/design/components/EditorForm/index.tsx
packages/design/components/EditorForm/style/index.less
packages/design/components/Form/Form.stories.tsx
packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
packages/design/components/Form/style/index.less
packages/design/components/Topic/style/Comment.less
packages/design/theme/base.less
packages/design/theme/mixins.less
packages/design/theme/variables.less
packages/website/src/pages/index/group/[name]/components/NewTopicForm.module.less
packages/website/src/pages/index/group/[name]/components/NewTopicForm.tsx
packages/website/src/pages/index/group/topic/[id]/index.module.less

ref: https://github.com/bangumi/frontend/pull/320#issuecomment-1427472398
close #361
禁用水平调宽，Editor 不设宽度（最小宽度为 EditorForm 宽度），最大宽度在 website 控制，如可以使用 `width:100%` ，`flex: 1` ，`flex-basis` 等

feat: BBcode editor disable horizontal resizing

---

.github/mergify.yml
packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
packages/utils/bbcode/__test__/react.test.tsx
packages/utils/bbcode/react.tsx

测试用例：
```
(bgm23)
(bgm13)
```
**Before:**
原 59 行的初始 Fragment 会变成数组 Fragment 的 children，如果数组内只有两个元素（`\n` -> `['', '']`），则最后生成的最外层 Fragment 的 key 就是最大索引值 1
**After:**

fix: duplicate key rendering `(bgm23)\n(bgm13)`

---

packages/website/src/components/Header/index.tsx
packages/website/src/pages/login/index.spec.tsx
packages/website/src/pages/login/index.tsx

Fix #480 
不知为何，在 Turnstile 验证码重置后 history state 会被替换，使得无法通过 `navigate(-1)` 返回上一页，例如在输错一次密码后
看了一下并没有找到原因，所以干脆把这个逻辑去掉，只留下根据 URL 传入的 backTo 进行跳转

fix: login redirect after captcha reset

---

packages/website/package.json
packages/website/src/App.tsx
packages/website/src/components/Helmet.tsx
packages/website/src/pages/index/group/[name]/__tests__/members.spec.tsx
packages/website/src/pages/index/group/[name]/index/forum.tsx
packages/website/src/pages/index/group/[name]/index/index.tsx
packages/website/src/pages/index/group/[name]/index/members.tsx
packages/website/src/pages/index/group/[name]/new_topic/index.tsx
packages/website/src/pages/index/group/reply/[id]/edit.tsx
packages/website/src/pages/index/group/topic/[id]/edit.tsx
packages/website/src/pages/index/group/topic/[id]/index.tsx
packages/website/src/pages/index/subject/[id]/components/WikiBeginnerEditor.spec.tsx
packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx
packages/website/src/pages/login/index.spec.tsx
packages/website/src/pages/login/index.tsx
packages/website/src/utils/test-utils.tsx
pnpm-lock.yaml

Fix #438 
未完成的页面（比如维基编辑历史）还没接入数据，就先不改了

fix: set page title

---

.github/actions/setup-js-env/action.yaml
package.json
pnpm-lock.yaml

把ci的`pnpm/actions-setup` 换成corepack了
应该不会影响不用corepack的开发者吧？

build: upgrade to pnpm to v8

---

packages/website/src/pages/login/index.spec.tsx
packages/website/src/pages/login/index.tsx
packages/website/src/utils/route.ts

现在登录后的转跳会使用 `window.location.replace` ，不再使用 `history.push`，允许转跳出SPA。

fix: jump out for oauth with login
