.github/workflows/build.yml
packages/website/vite.config.ts

Linux 文件名大小写敏感，MacOS 大小写不敏感，导致本地能够跑 build，但是在 Linux 上跑 build。这个 PR 将 `@bangumi/design` 库内的组件名约定为 `CapitalCase`。

ci: fix vercel preview

---

.eslintignore
.eslintrc.js
packages/design/.storybook/global.css
packages/design/.storybook/main.js
packages/design/.storybook/main.ts
packages/design/.storybook/preview-head.html
packages/design/.storybook/preview.js
packages/design/.storybook/preview.ts
packages/design/.storybook/tsconfig.json
packages/design/components/Menu/Menu.stories.tsx
packages/design/components/Menu/MenuItem.tsx
packages/design/components/Menu/__test__/Menu.spec.tsx
packages/design/components/Menu/index.tsx
packages/design/components/Menu/style/index.less
packages/design/components/Menu/style/index.tsx
packages/design/index.tsx
packages/design/package.json
pnpm-lock.yaml
tsconfig.json

Add normalize.css to Storybook
Storybook 配置文件改为 TS
完善 Storybook 添加 react-docgen 从 Props Interface 自动生成组件文档
设计的默认字体 Source Han Sans 目前暂时先用 Noto Sans（后续再讨论？）

feat(design): implement menu component

---

packages/design/.storybook/main.ts
packages/icons/index.stories.tsx
packages/icons/package.json
pnpm-lock.yaml

ref: https://github.com/bangumi/frontend/pull/47#pullrequestreview-901724998

refactor: add icons storybook

---

.github/workflows/unit-test.yml
.gitmodules
packages/utils/index.ts
packages/utils/package.json
packages/utils/wiki/__test__/parser.test.ts
packages/utils/wiki/error.ts
packages/utils/wiki/parser.ts
packages/utils/wiki/types.ts
pnpm-lock.yaml

https://github.com/bangumi/frontend/issues/53

feat(utils): Add parser for wiki

---

packages/design/components/Divider/__test__/Divider.spec.tsx
packages/design/components/Divider/index.tsx

fix(design): fix divider style

---

packages/website/src/components/Footer/index.tsx

refactor:copyright always  for the current year

---

packages/website/src/components/Footer/index.tsx
packages/website/src/components/Footer/style.module.less

fix:fix  footer bug #67

---

packages/design/components/Tab/Tab.stories.tsx
packages/design/components/Tab/__test__/Tab.spec.tsx
packages/design/components/Tab/index.tsx
packages/design/components/Tab/style/index.less

fix(design): fix tab class according to new convention

---

CONTRIBUTING.md

不加 `--recursive` 会无法通过 wiki 的测试用例

docs: fix contributing docs

---

packages/design/components/Typography/Text.tsx
packages/design/components/Typography/Typography.stories.tsx
packages/design/components/Typography/__test__/Texts.spec.tsx
packages/design/components/Typography/__test__/__snapshots__/Texts.spec.tsx.snap
packages/design/components/Typography/index.tsx
packages/design/components/Typography/style/Text.less
packages/design/components/Typography/style/index.tsx

feat(design): add typography

---

packages/design/components/Image/__test__/__snapshots__/index.spec.tsx.snap
packages/design/components/Image/index.tsx
packages/design/components/Image/style/index.less

Image 组件图片加载后底部露出来一点背景色。消掉露出来这点背景色，并且简化实现。

fix(design): fix unwanted background on the bottom of image

---

.github/workflows/preview-build.yml
.github/workflows/preview-storybook.yml

ci: upload master branch preview

---

packages/design/components/Tab/Tab.stories.tsx
packages/design/components/Tab/__test__/Tab.spec.tsx
packages/design/components/Tab/__test__/__snapshots__/Tab.spec.tsx.snap
packages/design/components/Tab/index.tsx
packages/design/components/Tab/style/index.less

feat(design): add borderless tab

---

.github/workflows/build.yml
package.json
packages/website/.env.test
packages/website/package.json
packages/website/src/api/request.ts
packages/website/src/hooks/use-user.tsx

使用 `https://dev.bgm38.com` 来 preview

build: use dev api for preview

---

packages/website/src/App.tsx
packages/website/src/pages/components/UserHome.tsx
packages/website/src/pages/group/[name]/index.tsx
packages/website/src/pages/group/[name]/members.tsx
packages/website/src/pages/index.tsx
packages/website/src/pages/subject/[id]/index.tsx
packages/website/src/utils/route.ts

通过路由判定是否展现 Layout
不用每一个路由引入 Layout
不需要等数据请求完成再显示首屏

refactor: determine whether to show layout by routing

---

package.json
packages/icons/package.json
pnpm-lock.yaml

hoist @types/testing-library__jest-dom

fix: type dependence missing(#120)

---

packages/website/src/pages/group/[name]/components/GroupHeader.tsx

fix: https://github.com/bangumi/frontend/issues/116

fix(issue 116): no icon group show

---

CONTRIBUTING.md
packages/website/package.json
packages/website/vite.config.ts

close https://github.com/bangumi/frontend/issues/188
试了一下是可以正常登录的，hCaptcha只是在localhost上不能工作，用127.0.0.1就可以了。

chore: start dev server at 127.0.0.1

---

packages/design/components/Button/__test__/Button.test.tsx
packages/design/components/Typography/__test__/Texts.spec.tsx
packages/website/src/hooks/use-user.spec.tsx
packages/website/src/pages/login/index.spec.tsx

重写了一下测试的写法，之前的写法没法自动推断类型（虽说也不是什么大问题）…

tests: rewrite table driven tests

---

packages/website/src/pages/login/index.tsx

close https://github.com/bangumi/frontend/issues/224

fix: reset hcaptcha when login failed

---

packages/website/src/hooks/use-user.tsx
packages/website/src/pages/login/index.spec.tsx
packages/website/src/pages/login/index.tsx

close https://github.com/bangumi/frontend/issues/228
不是很熟悉react，不知道这里有没有更好地写法，原来的FC写法只能透穿ref不能给ref赋值，所以只能改成class写法，并且因为init的原因得写在mock函数内。

tests: fix ref warning

---

packages/design/components/EditorForm/Editor.tsx
packages/design/components/EditorForm/EditorForm.stories.tsx
packages/design/components/EditorForm/Toolbox.tsx
packages/design/components/EditorForm/__test__/Editor.spec.tsx
packages/design/components/EditorForm/__test__/EditorForm.test.tsx
packages/design/components/EditorForm/index.tsx
packages/design/components/Topic/Comment.tsx
packages/design/components/Topic/CommentInfo.tsx
packages/design/components/Topic/ReplyForm.tsx
packages/design/components/Topic/__test__/Comment.spec.tsx
packages/design/package.json
packages/website/src/hooks/use-group-topic.ts
packages/website/src/hooks/use-group.ts
packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.tsx
packages/website/src/pages/index/group/topic/[id]/index.tsx
pnpm-lock.yaml

- Based on #251 
- Tracking issue: #235

feat: group topic reply

---

packages/design/components/EditorForm/Toolbox.tsx
packages/design/components/EditorForm/__test__/__snapshots__/Editor.spec.tsx.snap
packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
packages/design/components/EditorForm/__test__/__snapshots__/Toolbox.spec.tsx.snap
packages/website/vite.config.ts

feat: show tip for toolbox icons

---

.prettierignore
packages/design/components/RichContent/RichContent.stories.tsx
packages/design/components/RichContent/index.tsx
packages/design/components/Topic/Comment.tsx
packages/utils/bbcode/__test__/__snapshots__/html.test.ts.snap
packages/utils/bbcode/__test__/__snapshots__/react.test.tsx.snap
packages/utils/bbcode/__test__/convert.test.ts
packages/utils/bbcode/__test__/html.test.ts
packages/utils/bbcode/__test__/react.test.tsx
packages/utils/bbcode/convert.ts
packages/utils/bbcode/index.ts
packages/utils/bbcode/react.tsx
packages/utils/package.json
packages/website/src/pages/index/group/components/ClampableContent.tsx
packages/website/src/pages/index/group/topic/[id]/index.tsx
pnpm-lock.yaml

不直接使用 `dangerouslySetInnerHTML` , 而是用 `React.createElement` 来渲染 `bbcode`
相关 [issue](https://github.com/bangumi/frontend/issues/275)

fix: remove `dangerouslySetInnerHTML`

---

CONTRIBUTING.md

https://github.com/orgs/bangumi/projects/6/views/1

chore: add a tracking dashboard

---

packages/website/src/components/WikiEditor/WikiEditor.tsx

现在的 chunks 里混入了 monaco-editor 的各种内置语言：
<details>
```
vite v4.0.3 building for stage...
✓ 1241 modules transformed.
dist/assets/plus-75e89194.svg                    0.18 kB
dist/assets/minus-bc8fe00b.svg                   0.22 kB
dist/assets/topic-reopen-62568883.svg            0.30 kB
dist/assets/cursor-17777686.svg                  0.36 kB
dist/assets/bold-db10bc39.svg                    0.44 kB
dist/assets/italic-87d1a6c5.svg                  0.50 kB
dist/assets/close-quote-32ce538b.svg             0.53 kB
dist/assets/open-quote-522320d0.svg              0.54 kB
dist/assets/friend-a106e4c1.svg                  0.67 kB
dist/assets/topic-closed-2dfa8da8.svg            0.68 kB
dist/index.html                                  0.69 kB
dist/assets/size-6662d429.svg                    0.74 kB …
```

build: remove monaco-editor built-in languages

---

packages/website/src/pages/index/subject/[id]/wiki/edit_detail.tsx

fix: edit_detail typo

---

tsconfig.json

fix: ts path intelligent

---

packages/design/components/Topic/style/Comment.less

fix: collapsed comment style

---

packages/design/components/Input/Input.stories.tsx
packages/design/components/Input/style/index.less

如发送私信的表单
https://pr-353-storybook--bangumi-next.netlify.app/?path=/story/modern-input--text-prefix

feat(design): input text prefix

---

packages/design/components/EditorForm/Editor.tsx
packages/design/components/EditorForm/index.tsx
packages/design/components/EditorForm/style/index.less
packages/design/components/Form/Form.stories.tsx
packages/design/components/Form/__test__/Form.spec.tsx
packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
packages/design/components/Form/index.tsx
packages/design/components/Form/style/index.less
packages/design/components/Input/Input.stories.tsx
packages/design/components/Input/index.tsx
packages/design/components/Input/style/index.less

小组页面快速发帖和私信页面所用的紧凑版表单：
https://pr-351-storybook--bangumi-next.netlify.app/?path=/story/modern-form--compact

feat: compact form

---

packages/website/src/pages/index/subject/[id]/components/WikiLayout.module.less
packages/website/src/pages/index/subject/[id]/components/WikiLayout.tsx

feat: add link back to subject on wiki page

---

packages/design/components/EditorForm/Editor.tsx
packages/design/components/EditorForm/__test__/Editor.spec.tsx
packages/design/components/EditorForm/__test__/__snapshots__/Editor.spec.tsx.snap
packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
packages/design/components/EditorForm/style/index.less
packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap

设计稿里给编辑器增加了字数统计：
https://pr-357-storybook--bangumi-next.netlify.app/?path=/story/modern-editorform--usage

feat(Editor): word count

---

packages/design/components/EditorForm/Editor.tsx
packages/design/components/EditorForm/index.tsx
packages/design/components/EditorForm/style/index.less
packages/design/components/Form/Form.stories.tsx
packages/design/components/Form/__test__/Form.spec.tsx
packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap
packages/design/components/Form/style/index.less
packages/design/components/Input/index.tsx
packages/design/components/Input/style/index.less
packages/design/theme/base.less

close #364 
@FoundTheWOUT 
EditForm 的宽度我就不细调了，交给 #363 或等 #363 merge 了再调

refactor(design): compact form style

---

packages/website/src/pages/index/group/[name]/index/forum.tsx
packages/website/src/pages/index/group/[name]/index/index.tsx
packages/website/src/pages/index/group/components/GroupLayout.tsx
packages/website/src/pages/index/group/topic/[id]/index.tsx

fix: hide new post form & button if not logged in

---

packages/design/components/EditorForm/__test__/__snapshots__/EditorForm.test.tsx.snap
packages/design/components/EditorForm/index.tsx
packages/design/components/EditorForm/style/index.less
packages/design/components/Form/__test__/__snapshots__/Form.spec.tsx.snap

refactor: change submit buttons size to large

---

packages/design/components/Topic/Comment.tsx
packages/design/components/Topic/__test__/__snapshots__/Comment.spec.tsx.snap

- 折叠已删除的子评论
- 已删除评论不显示回复等按钮
- 组件拆分重构

fix: collapse & disable reply on deleted comments

---

packages/design/components/Topic/Comment.tsx
packages/design/components/Topic/__test__/Comment.spec.tsx
packages/website/src/pages/index/group/topic/[id]/index.tsx

feat: delete group reply

---

packages/website/vite.config.ts

build: build js/css files with .min.[ext]

---

.github/scripts/milestone.mts
.github/scripts/milestone.ts
.github/workflows/e2e-test.yml
.github/workflows/release.yml
package.json
pnpm-lock.yaml
tsconfig.json

release 的时候会把当前的 `next` milestone 修改为对应的版本名，然后创建一个新的 next milestone。
然后把原有milestone的剩余open issue移动到新的milestone。

ci: update and create new next milestone when release

---

packages/website/package.json
packages/website/tsconfig.json
pnpm-lock.yaml

~~fix https://github.com/bangumi/frontend/pull/473#discussion_r1156686423~~
follow https://github.com/bangumi/frontend/pull/534
tsc 不支持 ts 插件。。看来这个只能纯 DX，https://github.com/mrmckeb/typescript-plugin-css-modules/issues/57#issuecomment-544970525

Add typescript-plugin-css-modules

---

packages/client/api.yaml
packages/client/client.ts
packages/client/group.ts
packages/client/package.json
packages/client/types/index.ts
packages/website/src/hooks/use-group-members.ts
packages/website/src/hooks/use-group.ts
packages/website/src/pages/index/group/[name]/index/members.tsx
packages/website/src/pages/index/group/components/GroupActions.tsx
packages/website/src/pages/index/group/components/GroupHeader.tsx
packages/website/src/pages/index/group/components/GroupInfo.tsx
packages/website/src/pages/index/group/components/GroupLayout.tsx
packages/website/src/pages/index/group/components/GroupNavigation.tsx
packages/website/src/pages/index/group/topic/[id]/components/GroupTopicHeader.tsx
packages/website/src/pages/index/group/topic/[id]/index.tsx
packages/website/src/shared/wiki.ts
pnpm-lock.yaml

chore: update api spec
